/***************************************************
 * PEG Parser - Generated By YAPP Parser Generator *
 ***************************************************/

#ifndef JAVAPARSER_INCLUDE
#define JAVAPARSER_INCLUDE

#include "yapp_defs.h"
#include "yapp_node.h"
#include "yapp_buffer.h"
#include "yapp_rule.h"
#include "yapp_parser_error.h"
#include "yapp_trace_parser.h"
#include "yapp_mem_manager.h"

typedef struct {
   INT32 index;
   YAPP_BUFFER *buffer;
   YAPP_MEM_MANAGER *memoryManager;
   BOOL currentRuleIsAtomic;
   YAPP_NODE *currentNode;
   YAPP_NODE *lastNodeCreated;
   INT32 annotations_ruleMemoStart;
   INT32 annotations_ruleMemoEnd;
   YAPP_NODE *annotations_ruleMemoFirstNode;
   INT32 annotation_ruleMemoStart;
   INT32 annotation_ruleMemoEnd;
   YAPP_NODE *annotation_ruleMemoFirstNode;
   INT32 qualifiedIdentifier_ruleMemoStart;
   INT32 qualifiedIdentifier_ruleMemoEnd;
   YAPP_NODE *qualifiedIdentifier_ruleMemoFirstNode;
   INT32 modifiers_ruleMemoStart;
   INT32 modifiers_ruleMemoEnd;
   YAPP_NODE *modifiers_ruleMemoFirstNode;
   INT32 classDeclaration_ruleMemoStart;
   INT32 classDeclaration_ruleMemoEnd;
   YAPP_NODE *classDeclaration_ruleMemoFirstNode;
   INT32 enumDeclaration_ruleMemoStart;
   INT32 enumDeclaration_ruleMemoEnd;
   YAPP_NODE *enumDeclaration_ruleMemoFirstNode;
   INT32 interfaceDeclaration_ruleMemoStart;
   INT32 interfaceDeclaration_ruleMemoEnd;
   YAPP_NODE *interfaceDeclaration_ruleMemoFirstNode;
   INT32 annotationDeclaration_ruleMemoStart;
   INT32 annotationDeclaration_ruleMemoEnd;
   YAPP_NODE *annotationDeclaration_ruleMemoFirstNode;
   INT32 qualifiedClassName_ruleMemoStart;
   INT32 qualifiedClassName_ruleMemoEnd;
   YAPP_NODE *qualifiedClassName_ruleMemoFirstNode;
   INT32 implements_ruleMemoStart;
   INT32 implements_ruleMemoEnd;
   YAPP_NODE *implements_ruleMemoFirstNode;
   INT32 classTypeList_ruleMemoStart;
   INT32 classTypeList_ruleMemoEnd;
   YAPP_NODE *classTypeList_ruleMemoFirstNode;
   INT32 identifier_ruleMemoStart;
   INT32 identifier_ruleMemoEnd;
   YAPP_NODE *identifier_ruleMemoFirstNode;
   INT32 typeParameters_ruleMemoStart;
   INT32 typeParameters_ruleMemoEnd;
   YAPP_NODE *typeParameters_ruleMemoFirstNode;
   INT32 classBody_ruleMemoStart;
   INT32 classBody_ruleMemoEnd;
   YAPP_NODE *classBody_ruleMemoFirstNode;
   INT32 classBodyDeclaration_ruleMemoStart;
   INT32 classBodyDeclaration_ruleMemoEnd;
   YAPP_NODE *classBodyDeclaration_ruleMemoFirstNode;
   INT32 staticBlock_ruleMemoStart;
   INT32 staticBlock_ruleMemoEnd;
   YAPP_NODE *staticBlock_ruleMemoFirstNode;
   INT32 block_ruleMemoStart;
   INT32 block_ruleMemoEnd;
   YAPP_NODE *block_ruleMemoFirstNode;
   INT32 methodDeclaration_ruleMemoStart;
   INT32 methodDeclaration_ruleMemoEnd;
   YAPP_NODE *methodDeclaration_ruleMemoFirstNode;
   INT32 constructorDeclaration_ruleMemoStart;
   INT32 constructorDeclaration_ruleMemoEnd;
   YAPP_NODE *constructorDeclaration_ruleMemoFirstNode;
   INT32 fieldsDeclarations_ruleMemoStart;
   INT32 fieldsDeclarations_ruleMemoEnd;
   YAPP_NODE *fieldsDeclarations_ruleMemoFirstNode;
   INT32 type_ruleMemoStart;
   INT32 type_ruleMemoEnd;
   YAPP_NODE *type_ruleMemoFirstNode;
   INT32 variableDeclarations_ruleMemoStart;
   INT32 variableDeclarations_ruleMemoEnd;
   YAPP_NODE *variableDeclarations_ruleMemoFirstNode;
   INT32 throws_ruleMemoStart;
   INT32 throws_ruleMemoEnd;
   YAPP_NODE *throws_ruleMemoFirstNode;
   INT32 emptyBody_ruleMemoStart;
   INT32 emptyBody_ruleMemoEnd;
   YAPP_NODE *emptyBody_ruleMemoFirstNode;
   INT32 methodSignature_ruleMemoStart;
   INT32 methodSignature_ruleMemoEnd;
   YAPP_NODE *methodSignature_ruleMemoFirstNode;
   INT32 parametersDeclarations_ruleMemoStart;
   INT32 parametersDeclarations_ruleMemoEnd;
   YAPP_NODE *parametersDeclarations_ruleMemoFirstNode;
   INT32 dimensions_ruleMemoStart;
   INT32 dimensions_ruleMemoEnd;
   YAPP_NODE *dimensions_ruleMemoFirstNode;
   INT32 interfaceMethod_ruleMemoStart;
   INT32 interfaceMethod_ruleMemoEnd;
   YAPP_NODE *interfaceMethod_ruleMemoFirstNode;
   INT32 constantsDeclarations_ruleMemoStart;
   INT32 constantsDeclarations_ruleMemoEnd;
   YAPP_NODE *constantsDeclarations_ruleMemoFirstNode;
   INT32 constantDeclaration_ruleMemoStart;
   INT32 constantDeclaration_ruleMemoEnd;
   YAPP_NODE *constantDeclaration_ruleMemoFirstNode;
   INT32 variableInitializer_ruleMemoStart;
   INT32 variableInitializer_ruleMemoEnd;
   YAPP_NODE *variableInitializer_ruleMemoFirstNode;
   INT32 enumConstant_ruleMemoStart;
   INT32 enumConstant_ruleMemoEnd;
   YAPP_NODE *enumConstant_ruleMemoFirstNode;
   INT32 arguments_ruleMemoStart;
   INT32 arguments_ruleMemoEnd;
   YAPP_NODE *arguments_ruleMemoFirstNode;
   INT32 final_ruleMemoStart;
   INT32 final_ruleMemoEnd;
   YAPP_NODE *final_ruleMemoFirstNode;
   INT32 variableModifiers_ruleMemoStart;
   INT32 variableModifiers_ruleMemoEnd;
   YAPP_NODE *variableModifiers_ruleMemoFirstNode;
   INT32 localVariableDeclarationStatement_ruleMemoStart;
   INT32 localVariableDeclarationStatement_ruleMemoEnd;
   YAPP_NODE *localVariableDeclarationStatement_ruleMemoFirstNode;
   INT32 variableDeclaration_ruleMemoStart;
   INT32 variableDeclaration_ruleMemoEnd;
   YAPP_NODE *variableDeclaration_ruleMemoFirstNode;
   INT32 parametersDeclarationList_ruleMemoStart;
   INT32 parametersDeclarationList_ruleMemoEnd;
   YAPP_NODE *parametersDeclarationList_ruleMemoFirstNode;
   INT32 parameterDeclaration_ruleMemoStart;
   INT32 parameterDeclaration_ruleMemoEnd;
   YAPP_NODE *parameterDeclaration_ruleMemoFirstNode;
   INT32 parameterVariableDeclaration_ruleMemoStart;
   INT32 parameterVariableDeclaration_ruleMemoEnd;
   YAPP_NODE *parameterVariableDeclaration_ruleMemoFirstNode;
   INT32 blockStatements_ruleMemoStart;
   INT32 blockStatements_ruleMemoEnd;
   YAPP_NODE *blockStatements_ruleMemoFirstNode;
   INT32 statement_ruleMemoStart;
   INT32 statement_ruleMemoEnd;
   YAPP_NODE *statement_ruleMemoFirstNode;
   INT32 assertStatement_ruleMemoStart;
   INT32 assertStatement_ruleMemoEnd;
   YAPP_NODE *assertStatement_ruleMemoFirstNode;
   INT32 ifStatement_ruleMemoStart;
   INT32 ifStatement_ruleMemoEnd;
   YAPP_NODE *ifStatement_ruleMemoFirstNode;
   INT32 forStatement_ruleMemoStart;
   INT32 forStatement_ruleMemoEnd;
   YAPP_NODE *forStatement_ruleMemoFirstNode;
   INT32 forIterableStatement_ruleMemoStart;
   INT32 forIterableStatement_ruleMemoEnd;
   YAPP_NODE *forIterableStatement_ruleMemoFirstNode;
   INT32 whileStatement_ruleMemoStart;
   INT32 whileStatement_ruleMemoEnd;
   YAPP_NODE *whileStatement_ruleMemoFirstNode;
   INT32 doWhileStatement_ruleMemoStart;
   INT32 doWhileStatement_ruleMemoEnd;
   YAPP_NODE *doWhileStatement_ruleMemoFirstNode;
   INT32 tryCatchStatement_ruleMemoStart;
   INT32 tryCatchStatement_ruleMemoEnd;
   YAPP_NODE *tryCatchStatement_ruleMemoFirstNode;
   INT32 resource_ruleMemoStart;
   INT32 resource_ruleMemoEnd;
   YAPP_NODE *resource_ruleMemoFirstNode;
   INT32 switchStatement_ruleMemoStart;
   INT32 switchStatement_ruleMemoEnd;
   YAPP_NODE *switchStatement_ruleMemoFirstNode;
   INT32 synchronizedStatement_ruleMemoStart;
   INT32 synchronizedStatement_ruleMemoEnd;
   YAPP_NODE *synchronizedStatement_ruleMemoFirstNode;
   INT32 returnStatement_ruleMemoStart;
   INT32 returnStatement_ruleMemoEnd;
   YAPP_NODE *returnStatement_ruleMemoFirstNode;
   INT32 throwStatement_ruleMemoStart;
   INT32 throwStatement_ruleMemoEnd;
   YAPP_NODE *throwStatement_ruleMemoFirstNode;
   INT32 breakStatement_ruleMemoStart;
   INT32 breakStatement_ruleMemoEnd;
   YAPP_NODE *breakStatement_ruleMemoFirstNode;
   INT32 continueStatement_ruleMemoStart;
   INT32 continueStatement_ruleMemoEnd;
   YAPP_NODE *continueStatement_ruleMemoFirstNode;
   INT32 identifiedStatement_ruleMemoStart;
   INT32 identifiedStatement_ruleMemoEnd;
   YAPP_NODE *identifiedStatement_ruleMemoFirstNode;
   INT32 statementExpression_ruleMemoStart;
   INT32 statementExpression_ruleMemoEnd;
   YAPP_NODE *statementExpression_ruleMemoFirstNode;
   INT32 parExpression_ruleMemoStart;
   INT32 parExpression_ruleMemoEnd;
   YAPP_NODE *parExpression_ruleMemoFirstNode;
   INT32 expression_ruleMemoStart;
   INT32 expression_ruleMemoEnd;
   YAPP_NODE *expression_ruleMemoFirstNode;
   INT32 forInitVariables_ruleMemoStart;
   INT32 forInitVariables_ruleMemoEnd;
   YAPP_NODE *forInitVariables_ruleMemoFirstNode;
   INT32 forInitExpressions_ruleMemoStart;
   INT32 forInitExpressions_ruleMemoEnd;
   YAPP_NODE *forInitExpressions_ruleMemoFirstNode;
   INT32 assignmentExpression_ruleMemoStart;
   INT32 assignmentExpression_ruleMemoEnd;
   YAPP_NODE *assignmentExpression_ruleMemoFirstNode;
   INT32 conditionalExpression_ruleMemoStart;
   INT32 conditionalExpression_ruleMemoEnd;
   YAPP_NODE *conditionalExpression_ruleMemoFirstNode;
   INT32 ternaryExpression_ruleMemoStart;
   INT32 ternaryExpression_ruleMemoEnd;
   YAPP_NODE *ternaryExpression_ruleMemoFirstNode;
   INT32 conditionalOrExpression_ruleMemoStart;
   INT32 conditionalOrExpression_ruleMemoEnd;
   YAPP_NODE *conditionalOrExpression_ruleMemoFirstNode;
   INT32 orExpression_ruleMemoStart;
   INT32 orExpression_ruleMemoEnd;
   YAPP_NODE *orExpression_ruleMemoFirstNode;
   INT32 conditionalAndExpression_ruleMemoStart;
   INT32 conditionalAndExpression_ruleMemoEnd;
   YAPP_NODE *conditionalAndExpression_ruleMemoFirstNode;
   INT32 andExpression_ruleMemoStart;
   INT32 andExpression_ruleMemoEnd;
   YAPP_NODE *andExpression_ruleMemoFirstNode;
   INT32 optionalBitOrExpression_ruleMemoStart;
   INT32 optionalBitOrExpression_ruleMemoEnd;
   YAPP_NODE *optionalBitOrExpression_ruleMemoFirstNode;
   INT32 bitOrExpression_ruleMemoStart;
   INT32 bitOrExpression_ruleMemoEnd;
   YAPP_NODE *bitOrExpression_ruleMemoFirstNode;
   INT32 optionalBitXOrExpression_ruleMemoStart;
   INT32 optionalBitXOrExpression_ruleMemoEnd;
   YAPP_NODE *optionalBitXOrExpression_ruleMemoFirstNode;
   INT32 bitXOrExpression_ruleMemoStart;
   INT32 bitXOrExpression_ruleMemoEnd;
   YAPP_NODE *bitXOrExpression_ruleMemoFirstNode;
   INT32 optionalBitAndExpression_ruleMemoStart;
   INT32 optionalBitAndExpression_ruleMemoEnd;
   YAPP_NODE *optionalBitAndExpression_ruleMemoFirstNode;
   INT32 bitAndExpression_ruleMemoStart;
   INT32 bitAndExpression_ruleMemoEnd;
   YAPP_NODE *bitAndExpression_ruleMemoFirstNode;
   INT32 optionalRelationalExpression_ruleMemoStart;
   INT32 optionalRelationalExpression_ruleMemoEnd;
   YAPP_NODE *optionalRelationalExpression_ruleMemoFirstNode;
   INT32 relationalExpression_ruleMemoStart;
   INT32 relationalExpression_ruleMemoEnd;
   YAPP_NODE *relationalExpression_ruleMemoFirstNode;
   INT32 optionalInstanceOfExpression_ruleMemoStart;
   INT32 optionalInstanceOfExpression_ruleMemoEnd;
   YAPP_NODE *optionalInstanceOfExpression_ruleMemoFirstNode;
   INT32 instanceOfExpression_ruleMemoStart;
   INT32 instanceOfExpression_ruleMemoEnd;
   YAPP_NODE *instanceOfExpression_ruleMemoFirstNode;
   INT32 optionalAdditiveExpression_ruleMemoStart;
   INT32 optionalAdditiveExpression_ruleMemoEnd;
   YAPP_NODE *optionalAdditiveExpression_ruleMemoFirstNode;
   INT32 referenceType_ruleMemoStart;
   INT32 referenceType_ruleMemoEnd;
   YAPP_NODE *referenceType_ruleMemoFirstNode;
   INT32 additiveExpression_ruleMemoStart;
   INT32 additiveExpression_ruleMemoEnd;
   YAPP_NODE *additiveExpression_ruleMemoFirstNode;
   INT32 optionalMultiplicativeExpression_ruleMemoStart;
   INT32 optionalMultiplicativeExpression_ruleMemoEnd;
   YAPP_NODE *optionalMultiplicativeExpression_ruleMemoFirstNode;
   INT32 multiplicativeExpression_ruleMemoStart;
   INT32 multiplicativeExpression_ruleMemoEnd;
   YAPP_NODE *multiplicativeExpression_ruleMemoFirstNode;
   INT32 optionalShiftExpression_ruleMemoStart;
   INT32 optionalShiftExpression_ruleMemoEnd;
   YAPP_NODE *optionalShiftExpression_ruleMemoFirstNode;
   INT32 shiftExpression_ruleMemoStart;
   INT32 shiftExpression_ruleMemoEnd;
   YAPP_NODE *shiftExpression_ruleMemoFirstNode;
   INT32 unaryExpression_ruleMemoStart;
   INT32 unaryExpression_ruleMemoEnd;
   YAPP_NODE *unaryExpression_ruleMemoFirstNode;
   INT32 prefixedExpression_ruleMemoStart;
   INT32 prefixedExpression_ruleMemoEnd;
   YAPP_NODE *prefixedExpression_ruleMemoFirstNode;
   INT32 castExpression_ruleMemoStart;
   INT32 castExpression_ruleMemoEnd;
   YAPP_NODE *castExpression_ruleMemoFirstNode;
   INT32 postfixedExpression_ruleMemoStart;
   INT32 postfixedExpression_ruleMemoEnd;
   YAPP_NODE *postfixedExpression_ruleMemoFirstNode;
   INT32 primary_ruleMemoStart;
   INT32 primary_ruleMemoEnd;
   YAPP_NODE *primary_ruleMemoFirstNode;
   INT32 qualifiedExpression_ruleMemoStart;
   INT32 qualifiedExpression_ruleMemoEnd;
   YAPP_NODE *qualifiedExpression_ruleMemoFirstNode;
   INT32 arrayAccess_ruleMemoStart;
   INT32 arrayAccess_ruleMemoEnd;
   YAPP_NODE *arrayAccess_ruleMemoFirstNode;
   INT32 atomic_ruleMemoStart;
   INT32 atomic_ruleMemoEnd;
   YAPP_NODE *atomic_ruleMemoFirstNode;
   INT32 classTypeReference_ruleMemoStart;
   INT32 classTypeReference_ruleMemoEnd;
   YAPP_NODE *classTypeReference_ruleMemoFirstNode;
   INT32 literal_ruleMemoStart;
   INT32 literal_ruleMemoEnd;
   YAPP_NODE *literal_ruleMemoFirstNode;
   INT32 basicTypeClassReference_ruleMemoStart;
   INT32 basicTypeClassReference_ruleMemoEnd;
   YAPP_NODE *basicTypeClassReference_ruleMemoFirstNode;
   INT32 voidClassReference_ruleMemoStart;
   INT32 voidClassReference_ruleMemoEnd;
   YAPP_NODE *voidClassReference_ruleMemoFirstNode;
   INT32 thisMethodCall_ruleMemoStart;
   INT32 thisMethodCall_ruleMemoEnd;
   YAPP_NODE *thisMethodCall_ruleMemoFirstNode;
   INT32 this_ruleMemoStart;
   INT32 this_ruleMemoEnd;
   YAPP_NODE *this_ruleMemoFirstNode;
   INT32 super_ruleMemoStart;
   INT32 super_ruleMemoEnd;
   YAPP_NODE *super_ruleMemoFirstNode;
   INT32 superMethodCall_ruleMemoStart;
   INT32 superMethodCall_ruleMemoEnd;
   YAPP_NODE *superMethodCall_ruleMemoFirstNode;
   INT32 superConstructorCall_ruleMemoStart;
   INT32 superConstructorCall_ruleMemoEnd;
   YAPP_NODE *superConstructorCall_ruleMemoFirstNode;
   INT32 superFieldAccess_ruleMemoStart;
   INT32 superFieldAccess_ruleMemoEnd;
   YAPP_NODE *superFieldAccess_ruleMemoFirstNode;
   INT32 new_ruleMemoStart;
   INT32 new_ruleMemoEnd;
   YAPP_NODE *new_ruleMemoFirstNode;
   INT32 classCreator_ruleMemoStart;
   INT32 classCreator_ruleMemoEnd;
   YAPP_NODE *classCreator_ruleMemoFirstNode;
   INT32 arrayCreator_ruleMemoStart;
   INT32 arrayCreator_ruleMemoEnd;
   YAPP_NODE *arrayCreator_ruleMemoFirstNode;
   INT32 methodCall_ruleMemoStart;
   INT32 methodCall_ruleMemoEnd;
   YAPP_NODE *methodCall_ruleMemoFirstNode;
   INT32 dimExpr_ruleMemoStart;
   INT32 dimExpr_ruleMemoEnd;
   YAPP_NODE *dimExpr_ruleMemoFirstNode;
   INT32 basicType_ruleMemoStart;
   INT32 basicType_ruleMemoEnd;
   YAPP_NODE *basicType_ruleMemoFirstNode;
   INT32 nonWildcardTypeArguments_ruleMemoStart;
   INT32 nonWildcardTypeArguments_ruleMemoEnd;
   YAPP_NODE *nonWildcardTypeArguments_ruleMemoFirstNode;
   INT32 initializedArrayCreator_ruleMemoStart;
   INT32 initializedArrayCreator_ruleMemoEnd;
   YAPP_NODE *initializedArrayCreator_ruleMemoFirstNode;
   INT32 emptyArrayCreator_ruleMemoStart;
   INT32 emptyArrayCreator_ruleMemoEnd;
   YAPP_NODE *emptyArrayCreator_ruleMemoFirstNode;
   INT32 arrayType_ruleMemoStart;
   INT32 arrayType_ruleMemoEnd;
   YAPP_NODE *arrayType_ruleMemoFirstNode;
   INT32 dim_ruleMemoStart;
   INT32 dim_ruleMemoEnd;
   YAPP_NODE *dim_ruleMemoFirstNode;
   INT32 arrayInitializer_ruleMemoStart;
   INT32 arrayInitializer_ruleMemoEnd;
   YAPP_NODE *arrayInitializer_ruleMemoFirstNode;
   INT32 typedName_ruleMemoStart;
   INT32 typedName_ruleMemoEnd;
   YAPP_NODE *typedName_ruleMemoFirstNode;
   INT32 typeName_ruleMemoStart;
   INT32 typeName_ruleMemoEnd;
   YAPP_NODE *typeName_ruleMemoFirstNode;
   INT32 array_ruleMemoStart;
   INT32 array_ruleMemoEnd;
   YAPP_NODE *array_ruleMemoFirstNode;
   INT32 basicTypeArray_ruleMemoStart;
   INT32 basicTypeArray_ruleMemoEnd;
   YAPP_NODE *basicTypeArray_ruleMemoFirstNode;
   INT32 qualifiedClassNameArray_ruleMemoStart;
   INT32 qualifiedClassNameArray_ruleMemoEnd;
   YAPP_NODE *qualifiedClassNameArray_ruleMemoFirstNode;
   INT32 className_ruleMemoStart;
   INT32 className_ruleMemoEnd;
   YAPP_NODE *className_ruleMemoFirstNode;
   INT32 typedClassName_ruleMemoStart;
   INT32 typedClassName_ruleMemoEnd;
   YAPP_NODE *typedClassName_ruleMemoFirstNode;
   INT32 typeArgument_ruleMemoStart;
   INT32 typeArgument_ruleMemoEnd;
   YAPP_NODE *typeArgument_ruleMemoFirstNode;
   INT32 queryType_ruleMemoStart;
   INT32 queryType_ruleMemoEnd;
   YAPP_NODE *queryType_ruleMemoFirstNode;
   INT32 typeParameter_ruleMemoStart;
   INT32 typeParameter_ruleMemoEnd;
   YAPP_NODE *typeParameter_ruleMemoFirstNode;
   INT32 annotationMethod_ruleMemoStart;
   INT32 annotationMethod_ruleMemoEnd;
   YAPP_NODE *annotationMethod_ruleMemoFirstNode;
   INT32 annotationsConstants_ruleMemoStart;
   INT32 annotationsConstants_ruleMemoEnd;
   YAPP_NODE *annotationsConstants_ruleMemoFirstNode;
   INT32 elementValue_ruleMemoStart;
   INT32 elementValue_ruleMemoEnd;
   YAPP_NODE *elementValue_ruleMemoFirstNode;
   INT32 normalAnnotationRest_ruleMemoStart;
   INT32 normalAnnotationRest_ruleMemoEnd;
   YAPP_NODE *normalAnnotationRest_ruleMemoFirstNode;
   INT32 singleElementAnnotationRest_ruleMemoStart;
   INT32 singleElementAnnotationRest_ruleMemoEnd;
   YAPP_NODE *singleElementAnnotationRest_ruleMemoFirstNode;
   INT32 elementValuePair_ruleMemoStart;
   INT32 elementValuePair_ruleMemoEnd;
   YAPP_NODE *elementValuePair_ruleMemoFirstNode;
   INT32 elementValueArrayInitializer_ruleMemoStart;
   INT32 elementValueArrayInitializer_ruleMemoEnd;
   YAPP_NODE *elementValueArrayInitializer_ruleMemoFirstNode;
   INT32 testNoAlpha_ruleMemoStart;
   INT32 testNoAlpha_ruleMemoEnd;
   YAPP_NODE *testNoAlpha_ruleMemoFirstNode;
   INT32 optionalSpacing_ruleMemoStart;
   INT32 optionalSpacing_ruleMemoEnd;
   YAPP_NODE *optionalSpacing_ruleMemoFirstNode;
   INT32 spaces_ruleMemoStart;
   INT32 spaces_ruleMemoEnd;
   YAPP_NODE *spaces_ruleMemoFirstNode;
   INT32 blockComment_ruleMemoStart;
   INT32 blockComment_ruleMemoEnd;
   YAPP_NODE *blockComment_ruleMemoFirstNode;
   INT32 newLine_ruleMemoStart;
   INT32 newLine_ruleMemoEnd;
   YAPP_NODE *newLine_ruleMemoFirstNode;
   INT32 lineComment_ruleMemoStart;
   INT32 lineComment_ruleMemoEnd;
   YAPP_NODE *lineComment_ruleMemoFirstNode;
   INT32 floatLiteral_ruleMemoStart;
   INT32 floatLiteral_ruleMemoEnd;
   YAPP_NODE *floatLiteral_ruleMemoFirstNode;
   INT32 longLiteral_ruleMemoStart;
   INT32 longLiteral_ruleMemoEnd;
   YAPP_NODE *longLiteral_ruleMemoFirstNode;
   INT32 integerLiteral_ruleMemoStart;
   INT32 integerLiteral_ruleMemoEnd;
   YAPP_NODE *integerLiteral_ruleMemoFirstNode;
   INT32 charLiteral_ruleMemoStart;
   INT32 charLiteral_ruleMemoEnd;
   YAPP_NODE *charLiteral_ruleMemoFirstNode;
   INT32 stringLiteral_ruleMemoStart;
   INT32 stringLiteral_ruleMemoEnd;
   YAPP_NODE *stringLiteral_ruleMemoFirstNode;
   INT32 true_ruleMemoStart;
   INT32 true_ruleMemoEnd;
   YAPP_NODE *true_ruleMemoFirstNode;
   INT32 false_ruleMemoStart;
   INT32 false_ruleMemoEnd;
   YAPP_NODE *false_ruleMemoFirstNode;
   INT32 null_ruleMemoStart;
   INT32 null_ruleMemoEnd;
   YAPP_NODE *null_ruleMemoFirstNode;
   INT32 hexFloat_ruleMemoStart;
   INT32 hexFloat_ruleMemoEnd;
   YAPP_NODE *hexFloat_ruleMemoFirstNode;
   INT32 decimalFloat_ruleMemoStart;
   INT32 decimalFloat_ruleMemoEnd;
   YAPP_NODE *decimalFloat_ruleMemoFirstNode;
   INT32 semicolon_ruleMemoStart;
   INT32 semicolon_ruleMemoEnd;
   YAPP_NODE *semicolon_ruleMemoFirstNode;
} JavaParser;

extern YAPP_RULE TERMINAL_RULE;

extern YAPP_RULE JAVA_COMPILATION_UNIT;

extern YAPP_RULE JAVA_PACKAGE_DECLARATION;

extern YAPP_RULE JAVA_IMPORT_DECLARATION;

extern YAPP_RULE JAVA_TYPE_DECLARATION;

extern YAPP_RULE JAVA_ANNOTATIONS;

extern YAPP_RULE JAVA_ANNOTATION;

extern YAPP_RULE JAVA_QUALIFIED_IDENTIFIER;

extern YAPP_RULE JAVA_DOT_STAR;

extern YAPP_RULE JAVA_MODIFIERS;

extern YAPP_RULE JAVA_MODIFIER;

extern YAPP_RULE JAVA_CLASS_DECLARATION;

extern YAPP_RULE JAVA_ENUM_DECLARATION;

extern YAPP_RULE JAVA_INTERFACE_DECLARATION;

extern YAPP_RULE JAVA_ANNOTATION_DECLARATION;

extern YAPP_RULE JAVA_EXTENDS;

extern YAPP_RULE JAVA_QUALIFIED_CLASS_NAME;

extern YAPP_RULE JAVA_IMPLEMENTS;

extern YAPP_RULE JAVA_CLASS_TYPE_LIST;

extern YAPP_RULE JAVA_IDENTIFIER;

extern YAPP_RULE JAVA_TYPE_PARAMETERS;

extern YAPP_RULE JAVA_CLASS_BODY;

extern YAPP_RULE JAVA_CLASS_BODY_DECLARATION;

extern YAPP_RULE JAVA_STATIC_BLOCK;

extern YAPP_RULE JAVA_BLOCK;

extern YAPP_RULE JAVA_METHOD_DECLARATION;

extern YAPP_RULE JAVA_CONSTRUCTOR_DECLARATION;

extern YAPP_RULE JAVA_FIELDS_DECLARATIONS;

extern YAPP_RULE JAVA_TYPE;

extern YAPP_RULE JAVA_VARIABLE_DECLARATIONS;

extern YAPP_RULE JAVA_THROWS;

extern YAPP_RULE JAVA_EMPTY_BODY;

extern YAPP_RULE JAVA_RETURN_TYPE;

extern YAPP_RULE JAVA_METHOD_SIGNATURE;

extern YAPP_RULE JAVA_PARAMETERS_DECLARATIONS;

extern YAPP_RULE JAVA_DIMENSIONS;

extern YAPP_RULE JAVA_INTERFACE_BODY;

extern YAPP_RULE JAVA_INTERFACE_BODY_DECLARATION;

extern YAPP_RULE JAVA_INTERFACE_METHOD;

extern YAPP_RULE JAVA_CONSTANTS_DECLARATIONS;

extern YAPP_RULE JAVA_CONSTANTS_DECLARATIONS_LIST;

extern YAPP_RULE JAVA_CONSTANT_DECLARATION;

extern YAPP_RULE JAVA_VARIABLE_INITIALIZER;

extern YAPP_RULE JAVA_ENUM_BODY;

extern YAPP_RULE JAVA_ENUM_CONSTANTS;

extern YAPP_RULE JAVA_ENUM_BODY_DECLARATIONS;

extern YAPP_RULE JAVA_ENUM_CONSTANT;

extern YAPP_RULE JAVA_ARGUMENTS;

extern YAPP_RULE JAVA_FINAL;

extern YAPP_RULE JAVA_VARIABLE_MODIFIERS;

extern YAPP_RULE JAVA_LOCAL_VARIABLE_DECLARATION_STATEMENT;

extern YAPP_RULE JAVA_VARIABLE_DECLARATION;

extern YAPP_RULE JAVA_VARIABLE_INITIALIZATION;

extern YAPP_RULE JAVA_PARAMETERS_DECLARATION_LIST;

extern YAPP_RULE JAVA_PARAMETER_DECLARATION;

extern YAPP_RULE JAVA_PARAMETER_VARIABLE_DECLARATION;

extern YAPP_RULE JAVA_BLOCK_STATEMENTS;

extern YAPP_RULE JAVA_BLOCK_STATEMENT;

extern YAPP_RULE JAVA_STATEMENT;

extern YAPP_RULE JAVA_ASSERT_STATEMENT;

extern YAPP_RULE JAVA_IF_STATEMENT;

extern YAPP_RULE JAVA_FOR_STATEMENT;

extern YAPP_RULE JAVA_FOR_ITERABLE_STATEMENT;

extern YAPP_RULE JAVA_WHILE_STATEMENT;

extern YAPP_RULE JAVA_DO_WHILE_STATEMENT;

extern YAPP_RULE JAVA_TRY_CATCH_STATEMENT;

extern YAPP_RULE JAVA_RESOURCE_SPECIFICATION;

extern YAPP_RULE JAVA_RESOURCES;

extern YAPP_RULE JAVA_RESOURCE;

extern YAPP_RULE JAVA_SWITCH_STATEMENT;

extern YAPP_RULE JAVA_SYNCHRONIZED_STATEMENT;

extern YAPP_RULE JAVA_RETURN_STATEMENT;

extern YAPP_RULE JAVA_THROW_STATEMENT;

extern YAPP_RULE JAVA_BREAK_STATEMENT;

extern YAPP_RULE JAVA_CONTINUE_STATEMENT;

extern YAPP_RULE JAVA_IDENTIFIED_STATEMENT;

extern YAPP_RULE JAVA_STATEMENT_EXPRESSION;

extern YAPP_RULE JAVA_ELSE_STATEMENT;

extern YAPP_RULE JAVA_PAR_EXPRESSION;

extern YAPP_RULE JAVA_EXPRESSION;

extern YAPP_RULE JAVA_FOR_INIT;

extern YAPP_RULE JAVA_FOR_UPDATE;

extern YAPP_RULE JAVA_CATCH_TYPE;

extern YAPP_RULE JAVA_CATCH_PARAMETER;

extern YAPP_RULE JAVA_CATCH;

extern YAPP_RULE JAVA_FINALLY;

extern YAPP_RULE JAVA_SWITCH_BLOCK_STATEMENT_GROUPS;

extern YAPP_RULE JAVA_SWITCH_BLOCK_STATEMENT_GROUP;

extern YAPP_RULE JAVA_SWITCH_LABEL;

extern YAPP_RULE JAVA_ENUM_CONSTANT_NAME;

extern YAPP_RULE JAVA_FOR_INIT_VARIABLES;

extern YAPP_RULE JAVA_FOR_INIT_EXPRESSIONS;

extern YAPP_RULE JAVA_ASSIGNMENT_EXPRESSION;

extern YAPP_RULE JAVA_CONDITIONAL_EXPRESSION;

extern YAPP_RULE JAVA_ASSIGNMENT_OPERATOR;

extern YAPP_RULE JAVA_TERNARY_EXPRESSION;

extern YAPP_RULE JAVA_CONDITIONAL_OR_EXPRESSION;

extern YAPP_RULE JAVA_OR_EXPRESSION;

extern YAPP_RULE JAVA_CONDITIONAL_AND_EXPRESSION;

extern YAPP_RULE JAVA_AND_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_BIT_OR_EXPRESSION;

extern YAPP_RULE JAVA_BIT_OR_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_BIT_XOR_EXPRESSION;

extern YAPP_RULE JAVA_BIT_XOR_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_BIT_AND_EXPRESSION;

extern YAPP_RULE JAVA_BIT_AND_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_RELATIONAL_EXPRESSION;

extern YAPP_RULE JAVA_RELATIONAL_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_INSTANCE_OF_EXPRESSION;

extern YAPP_RULE JAVA_INSTANCE_OF_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_ADDITIVE_EXPRESSION;

extern YAPP_RULE JAVA_REFERENCE_TYPE;

extern YAPP_RULE JAVA_ADDITIVE_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_MULTIPLICATIVE_EXPRESSION;

extern YAPP_RULE JAVA_MULTIPLICATIVE_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_SHIFT_EXPRESSION;

extern YAPP_RULE JAVA_SHIFT_EXPRESSION;

extern YAPP_RULE JAVA_UNARY_EXPRESSION;

extern YAPP_RULE JAVA_PREFIXED_EXPRESSION;

extern YAPP_RULE JAVA_CAST_EXPRESSION;

extern YAPP_RULE JAVA_POSTFIXED_EXPRESSION;

extern YAPP_RULE JAVA_PREFIX_OP;

extern YAPP_RULE JAVA_POST_FIX_OP;

extern YAPP_RULE JAVA_PRIMARY;

extern YAPP_RULE JAVA_QUALIFIED_EXPRESSION;

extern YAPP_RULE JAVA_ARRAY_ACCESS;

extern YAPP_RULE JAVA_ATOMIC;

extern YAPP_RULE JAVA_CLASS_TYPE_REFERENCE;

extern YAPP_RULE JAVA_LITERAL;

extern YAPP_RULE JAVA_BASIC_TYPE_CLASS_REFERENCE;

extern YAPP_RULE JAVA_VOID_CLASS_REFERENCE;

extern YAPP_RULE JAVA_THIS_METHOD_CALL;

extern YAPP_RULE JAVA_THIS;

extern YAPP_RULE JAVA_SUPER;

extern YAPP_RULE JAVA_SUPER_METHOD_CALL;

extern YAPP_RULE JAVA_SUPER_CONSTRUCTOR_CALL;

extern YAPP_RULE JAVA_SUPER_FIELD_ACCESS;

extern YAPP_RULE JAVA_NEW;

extern YAPP_RULE JAVA_CLASS_CREATOR;

extern YAPP_RULE JAVA_ARRAY_CREATOR;

extern YAPP_RULE JAVA_METHOD_CALL;

extern YAPP_RULE JAVA_ARRAY_INDEX;

extern YAPP_RULE JAVA_DIM_EXPR;

extern YAPP_RULE JAVA_BASIC_TYPE;

extern YAPP_RULE JAVA_NON_WILDCARD_TYPE_ARGUMENTS;

extern YAPP_RULE JAVA_CREATED_NAME;

extern YAPP_RULE JAVA_INITIALIZED_ARRAY_CREATOR;

extern YAPP_RULE JAVA_EMPTY_ARRAY_CREATOR;

extern YAPP_RULE JAVA_ARRAY_TYPE;

extern YAPP_RULE JAVA_DIM;

extern YAPP_RULE JAVA_ARRAY_INITIALIZER;

extern YAPP_RULE JAVA_TYPED_NAME;

extern YAPP_RULE JAVA_TYPE_NAME;

extern YAPP_RULE JAVA_ARRAY;

extern YAPP_RULE JAVA_BASIC_TYPE_ARRAY;

extern YAPP_RULE JAVA_QUALIFIED_CLASS_NAME_ARRAY;

extern YAPP_RULE JAVA_CLASS_NAME;

extern YAPP_RULE JAVA_TYPED_CLASS_NAME;

extern YAPP_RULE JAVA_TYPE_ARGUMENTS;

extern YAPP_RULE JAVA_TYPE_ARGUMENT;

extern YAPP_RULE JAVA_QUERY_TYPE;

extern YAPP_RULE JAVA_TYPE_PARAMETER;

extern YAPP_RULE JAVA_BOUND;

extern YAPP_RULE JAVA_ANNOTATION_TYPE_BODY;

extern YAPP_RULE JAVA_ANNOTATION_TYPE_ELEMENT_DECLARATION;

extern YAPP_RULE JAVA_ANNOTATION_METHOD;

extern YAPP_RULE JAVA_ANNOTATIONS_CONSTANTS;

extern YAPP_RULE JAVA_DEFAULT_VALUE;

extern YAPP_RULE JAVA_ELEMENT_VALUE;

extern YAPP_RULE JAVA_ANNOTATION_PARAMETERS;

extern YAPP_RULE JAVA_NORMAL_ANNOTATION_REST;

extern YAPP_RULE JAVA_SINGLE_ELEMENT_ANNOTATION_REST;

extern YAPP_RULE JAVA_ELEMENT_VALUE_PAIRS;

extern YAPP_RULE JAVA_ELEMENT_VALUE_PAIR;

extern YAPP_RULE JAVA_ELEMENT_VALUE_ARRAY_INITIALIZER;

extern YAPP_RULE JAVA_ELEMENT_VALUES;

extern YAPP_RULE JAVA_TEST_NO_ALPHA;

extern YAPP_RULE JAVA_SPACING;

extern YAPP_RULE JAVA_SPACES;

extern YAPP_RULE JAVA_BLOCK_COMMENT;

extern YAPP_RULE JAVA_NEW_LINE;

extern YAPP_RULE JAVA_LINE_COMMENT;

extern YAPP_RULE JAVA_FLOAT_LITERAL;

extern YAPP_RULE JAVA_LONG_LITERAL;

extern YAPP_RULE JAVA_INTEGER_LITERAL;

extern YAPP_RULE JAVA_CHAR_LITERAL;

extern YAPP_RULE JAVA_STRING_LITERAL;

extern YAPP_RULE JAVA_TRUE;

extern YAPP_RULE JAVA_FALSE;

extern YAPP_RULE JAVA_NULL;

extern YAPP_RULE JAVA_HEX_FLOAT;

extern YAPP_RULE JAVA_DECIMAL_FLOAT;

extern YAPP_RULE JAVA_SEMICOLON;

extern YAPP_NODE* javaParser_parse(JavaParser *parser);
extern JavaParser* javaParser_new(YAPP_BUFFER *inputBuffer);
extern JavaParser* javaParser_newManaged(YAPP_MEM_MANAGER *memoryManager, YAPP_BUFFER *inputBuffer);
extern void javaParser_free(JavaParser *parser);
extern void javaParser_setTraceParser(JavaParser *parser, YAPP_TRACE_PARSER *tracePath);
extern void javaParser_setTrace(JavaParser *parser, BOOL trace);
extern YAPP_PARSER_ERROR* javaParser_getMismatches(JavaParser *parser);
#endif
