/***************************************************
 * PEG Parser - Generated By YAPP Parser Generator *
 ***************************************************/

#ifndef JAVAPARSER_INCLUDE
#define JAVAPARSER_INCLUDE

#include "yapp_defs.h"
#include "yapp_node.h"
#include "yapp_buffer.h"
#include "yapp_rule.h"
#include "yapp_parser_error.h"
#include "yapp_trace_parser.h"
#include "yapp_mem_manager.h"

typedef struct {
   INT32 index;
   YAPP_BUFFER *buffer;
   YAPP_MEM_MANAGER *memoryManager;
   BOOL currentRuleIsAtomic;
   YAPP_NODE *currentNode;
   YAPP_NODE *lastNodeCreated;
   INT32 annotation_ruleMemoStart;
   INT32 annotation_ruleMemoEnd;
   YAPP_NODE *annotation_ruleMemoFirstNode;
   YAPP_NODE *annotation_ruleMemoLastNode;
   INT32 modifiers_ruleMemoStart;
   INT32 modifiers_ruleMemoEnd;
   YAPP_NODE *modifiers_ruleMemoFirstNode;
   YAPP_NODE *modifiers_ruleMemoLastNode;
   INT32 qualifiedClassName_ruleMemoStart;
   INT32 qualifiedClassName_ruleMemoEnd;
   YAPP_NODE *qualifiedClassName_ruleMemoFirstNode;
   YAPP_NODE *qualifiedClassName_ruleMemoLastNode;
   INT32 identifier_ruleMemoStart;
   INT32 identifier_ruleMemoEnd;
   YAPP_NODE *identifier_ruleMemoFirstNode;
   YAPP_NODE *identifier_ruleMemoLastNode;
   INT32 typeParameters_ruleMemoStart;
   INT32 typeParameters_ruleMemoEnd;
   YAPP_NODE *typeParameters_ruleMemoFirstNode;
   YAPP_NODE *typeParameters_ruleMemoLastNode;
   INT32 type_ruleMemoStart;
   INT32 type_ruleMemoEnd;
   YAPP_NODE *type_ruleMemoFirstNode;
   YAPP_NODE *type_ruleMemoLastNode;
   INT32 dimensions_ruleMemoStart;
   INT32 dimensions_ruleMemoEnd;
   YAPP_NODE *dimensions_ruleMemoFirstNode;
   YAPP_NODE *dimensions_ruleMemoLastNode;
   INT32 parameterDeclaration_ruleMemoStart;
   INT32 parameterDeclaration_ruleMemoEnd;
   YAPP_NODE *parameterDeclaration_ruleMemoFirstNode;
   YAPP_NODE *parameterDeclaration_ruleMemoLastNode;
   INT32 conditionalExpression_ruleMemoStart;
   INT32 conditionalExpression_ruleMemoEnd;
   YAPP_NODE *conditionalExpression_ruleMemoFirstNode;
   YAPP_NODE *conditionalExpression_ruleMemoLastNode;
   INT32 assignmentOperator_ruleMemoStart;
   INT32 assignmentOperator_ruleMemoEnd;
   YAPP_NODE *assignmentOperator_ruleMemoFirstNode;
   YAPP_NODE *assignmentOperator_ruleMemoLastNode;
   INT32 conditionalOrExpression_ruleMemoStart;
   INT32 conditionalOrExpression_ruleMemoEnd;
   YAPP_NODE *conditionalOrExpression_ruleMemoFirstNode;
   YAPP_NODE *conditionalOrExpression_ruleMemoLastNode;
   INT32 conditionalAndExpression_ruleMemoStart;
   INT32 conditionalAndExpression_ruleMemoEnd;
   YAPP_NODE *conditionalAndExpression_ruleMemoFirstNode;
   YAPP_NODE *conditionalAndExpression_ruleMemoLastNode;
   INT32 optionalBitOrExpression_ruleMemoStart;
   INT32 optionalBitOrExpression_ruleMemoEnd;
   YAPP_NODE *optionalBitOrExpression_ruleMemoFirstNode;
   YAPP_NODE *optionalBitOrExpression_ruleMemoLastNode;
   INT32 optionalBitXOrExpression_ruleMemoStart;
   INT32 optionalBitXOrExpression_ruleMemoEnd;
   YAPP_NODE *optionalBitXOrExpression_ruleMemoFirstNode;
   YAPP_NODE *optionalBitXOrExpression_ruleMemoLastNode;
   INT32 optionalBitAndExpression_ruleMemoStart;
   INT32 optionalBitAndExpression_ruleMemoEnd;
   YAPP_NODE *optionalBitAndExpression_ruleMemoFirstNode;
   YAPP_NODE *optionalBitAndExpression_ruleMemoLastNode;
   INT32 optionalRelationalExpression_ruleMemoStart;
   INT32 optionalRelationalExpression_ruleMemoEnd;
   YAPP_NODE *optionalRelationalExpression_ruleMemoFirstNode;
   YAPP_NODE *optionalRelationalExpression_ruleMemoLastNode;
   INT32 optionalInstanceOfExpression_ruleMemoStart;
   INT32 optionalInstanceOfExpression_ruleMemoEnd;
   YAPP_NODE *optionalInstanceOfExpression_ruleMemoFirstNode;
   YAPP_NODE *optionalInstanceOfExpression_ruleMemoLastNode;
   INT32 optionalAdditiveExpression_ruleMemoStart;
   INT32 optionalAdditiveExpression_ruleMemoEnd;
   YAPP_NODE *optionalAdditiveExpression_ruleMemoFirstNode;
   YAPP_NODE *optionalAdditiveExpression_ruleMemoLastNode;
   INT32 referenceType_ruleMemoStart;
   INT32 referenceType_ruleMemoEnd;
   YAPP_NODE *referenceType_ruleMemoFirstNode;
   YAPP_NODE *referenceType_ruleMemoLastNode;
   INT32 optionalMultiplicativeExpression_ruleMemoStart;
   INT32 optionalMultiplicativeExpression_ruleMemoEnd;
   YAPP_NODE *optionalMultiplicativeExpression_ruleMemoFirstNode;
   YAPP_NODE *optionalMultiplicativeExpression_ruleMemoLastNode;
   INT32 optionalShiftExpression_ruleMemoStart;
   INT32 optionalShiftExpression_ruleMemoEnd;
   YAPP_NODE *optionalShiftExpression_ruleMemoFirstNode;
   YAPP_NODE *optionalShiftExpression_ruleMemoLastNode;
   INT32 unaryExpression_ruleMemoStart;
   INT32 unaryExpression_ruleMemoEnd;
   YAPP_NODE *unaryExpression_ruleMemoFirstNode;
   YAPP_NODE *unaryExpression_ruleMemoLastNode;
   INT32 primary_ruleMemoStart;
   INT32 primary_ruleMemoEnd;
   YAPP_NODE *primary_ruleMemoFirstNode;
   YAPP_NODE *primary_ruleMemoLastNode;
   INT32 atomic_ruleMemoStart;
   INT32 atomic_ruleMemoEnd;
   YAPP_NODE *atomic_ruleMemoFirstNode;
   YAPP_NODE *atomic_ruleMemoLastNode;
   INT32 this_ruleMemoStart;
   INT32 this_ruleMemoEnd;
   YAPP_NODE *this_ruleMemoFirstNode;
   YAPP_NODE *this_ruleMemoLastNode;
   INT32 super_ruleMemoStart;
   INT32 super_ruleMemoEnd;
   YAPP_NODE *super_ruleMemoFirstNode;
   YAPP_NODE *super_ruleMemoLastNode;
   INT32 new_ruleMemoStart;
   INT32 new_ruleMemoEnd;
   YAPP_NODE *new_ruleMemoFirstNode;
   YAPP_NODE *new_ruleMemoLastNode;
   INT32 methodCall_ruleMemoStart;
   INT32 methodCall_ruleMemoEnd;
   YAPP_NODE *methodCall_ruleMemoFirstNode;
   YAPP_NODE *methodCall_ruleMemoLastNode;
   INT32 arrayIndex_ruleMemoStart;
   INT32 arrayIndex_ruleMemoEnd;
   YAPP_NODE *arrayIndex_ruleMemoFirstNode;
   YAPP_NODE *arrayIndex_ruleMemoLastNode;
   INT32 basicType_ruleMemoStart;
   INT32 basicType_ruleMemoEnd;
   YAPP_NODE *basicType_ruleMemoFirstNode;
   YAPP_NODE *basicType_ruleMemoLastNode;
   INT32 spacing_ruleMemoStart;
   INT32 spacing_ruleMemoEnd;
   YAPP_NODE *spacing_ruleMemoFirstNode;
   YAPP_NODE *spacing_ruleMemoLastNode;
   INT32 optionalSpacing_ruleMemoStart;
   INT32 optionalSpacing_ruleMemoEnd;
   YAPP_NODE *optionalSpacing_ruleMemoFirstNode;
   YAPP_NODE *optionalSpacing_ruleMemoLastNode;
   INT32 integerLiteral_ruleMemoStart;
   INT32 integerLiteral_ruleMemoEnd;
   YAPP_NODE *integerLiteral_ruleMemoFirstNode;
   YAPP_NODE *integerLiteral_ruleMemoLastNode;
} JavaParser;

extern YAPP_RULE TERMINAL_RULE;

extern YAPP_RULE JAVA_COMPILATION_UNIT;

extern YAPP_RULE JAVA_PACKAGE_DECLARATION;

extern YAPP_RULE JAVA_IMPORT_DECLARATION;

extern YAPP_RULE JAVA_TYPE_DECLARATION;

extern YAPP_RULE JAVA_ANNOTATIONS;

extern YAPP_RULE JAVA_ANNOTATION;

extern YAPP_RULE JAVA_QUALIFIED_IDENTIFIER;

extern YAPP_RULE JAVA_DOT_STAR;

extern YAPP_RULE JAVA_MODIFIERS;

extern YAPP_RULE JAVA_MODIFIER;

extern YAPP_RULE JAVA_CLASS_DECLARATION;

extern YAPP_RULE JAVA_ENUM_DECLARATION;

extern YAPP_RULE JAVA_INTERFACE_DECLARATION;

extern YAPP_RULE JAVA_ANNOTATION_DECLARATION;

extern YAPP_RULE JAVA_EXTENDS;

extern YAPP_RULE JAVA_QUALIFIED_CLASS_NAME;

extern YAPP_RULE JAVA_IMPLEMENTS;

extern YAPP_RULE JAVA_CLASS_TYPE_LIST;

extern YAPP_RULE JAVA_IDENTIFIER;

extern YAPP_RULE JAVA_TYPE_PARAMETERS;

extern YAPP_RULE JAVA_CLASS_BODY;

extern YAPP_RULE JAVA_CLASS_BODY_DECLARATION;

extern YAPP_RULE JAVA_STATIC_BLOCK;

extern YAPP_RULE JAVA_BLOCK;

extern YAPP_RULE JAVA_METHOD_DECLARATION;

extern YAPP_RULE JAVA_CONSTRUCTOR_DECLARATION;

extern YAPP_RULE JAVA_FIELDS_DECLARATIONS;

extern YAPP_RULE JAVA_TYPE;

extern YAPP_RULE JAVA_VARIABLE_DECLARATIONS;

extern YAPP_RULE JAVA_THROWS;

extern YAPP_RULE JAVA_EMPTY_BODY;

extern YAPP_RULE JAVA_RETURN_TYPE;

extern YAPP_RULE JAVA_METHOD_SIGNATURE;

extern YAPP_RULE JAVA_PARAMETERS_DECLARATIONS;

extern YAPP_RULE JAVA_DIMENSIONS;

extern YAPP_RULE JAVA_INTERFACE_BODY;

extern YAPP_RULE JAVA_INTERFACE_BODY_DECLARATION;

extern YAPP_RULE JAVA_INTERFACE_METHOD;

extern YAPP_RULE JAVA_CONSTANTS_DECLARATIONS;

extern YAPP_RULE JAVA_CONSTANTS_DECLARATIONS_LIST;

extern YAPP_RULE JAVA_CONSTANT_DECLARATION;

extern YAPP_RULE JAVA_VARIABLE_INITIALIZER;

extern YAPP_RULE JAVA_ENUM_BODY;

extern YAPP_RULE JAVA_ENUM_CONSTANTS;

extern YAPP_RULE JAVA_ENUM_BODY_DECLARATIONS;

extern YAPP_RULE JAVA_ENUM_CONSTANT;

extern YAPP_RULE JAVA_ARGUMENTS;

extern YAPP_RULE JAVA_FINAL;

extern YAPP_RULE JAVA_VARIABLE_MODIFIERS;

extern YAPP_RULE JAVA_LOCAL_VARIABLE_DECLARATION_STATEMENT;

extern YAPP_RULE JAVA_VARIABLE_DECLARATION;

extern YAPP_RULE JAVA_VARIABLE_INITIALIZATION;

extern YAPP_RULE JAVA_PARAMETERS_DECLARATION_LIST;

extern YAPP_RULE JAVA_PARAMETER_DECLARATION;

extern YAPP_RULE JAVA_PARAMETER_VARIABLE_DECLARATION;

extern YAPP_RULE JAVA_BLOCK_STATEMENTS;

extern YAPP_RULE JAVA_BLOCK_STATEMENT;

extern YAPP_RULE JAVA_STATEMENT;

extern YAPP_RULE JAVA_ASSERT_STATEMENT;

extern YAPP_RULE JAVA_IF_STATEMENT;

extern YAPP_RULE JAVA_FOR_STATEMENT;

extern YAPP_RULE JAVA_FOR_ITERABLE_STATEMENT;

extern YAPP_RULE JAVA_WHILE_STATEMENT;

extern YAPP_RULE JAVA_DO_WHILE_STATEMENT;

extern YAPP_RULE JAVA_TRY_CATCH_STATEMENT;

extern YAPP_RULE JAVA_RESOURCE_SPECIFICATION;

extern YAPP_RULE JAVA_RESOURCES;

extern YAPP_RULE JAVA_RESOURCE;

extern YAPP_RULE JAVA_SWITCH_STATEMENT;

extern YAPP_RULE JAVA_SYNCHRONIZED_STATEMENT;

extern YAPP_RULE JAVA_RETURN_STATEMENT;

extern YAPP_RULE JAVA_THROW_STATEMENT;

extern YAPP_RULE JAVA_BREAK_STATEMENT;

extern YAPP_RULE JAVA_CONTINUE_STATEMENT;

extern YAPP_RULE JAVA_IDENTIFIED_STATEMENT;

extern YAPP_RULE JAVA_STATEMENT_EXPRESSION;

extern YAPP_RULE JAVA_ELSE_STATEMENT;

extern YAPP_RULE JAVA_PAR_EXPRESSION;

extern YAPP_RULE JAVA_EXPRESSION;

extern YAPP_RULE JAVA_FOR_INIT;

extern YAPP_RULE JAVA_FOR_UPDATE;

extern YAPP_RULE JAVA_CATCH_TYPE;

extern YAPP_RULE JAVA_CATCH_PARAMETER;

extern YAPP_RULE JAVA_CATCH;

extern YAPP_RULE JAVA_FINALLY;

extern YAPP_RULE JAVA_SWITCH_BLOCK_STATEMENT_GROUPS;

extern YAPP_RULE JAVA_SWITCH_BLOCK_STATEMENT_GROUP;

extern YAPP_RULE JAVA_SWITCH_LABEL;

extern YAPP_RULE JAVA_ENUM_CONSTANT_NAME;

extern YAPP_RULE JAVA_FOR_INIT_VARIABLES;

extern YAPP_RULE JAVA_FOR_INIT_EXPRESSIONS;

extern YAPP_RULE JAVA_ASSIGNMENT_EXPRESSION;

extern YAPP_RULE JAVA_CONDITIONAL_EXPRESSION;

extern YAPP_RULE JAVA_ASSIGNMENT_OPERATOR;

extern YAPP_RULE JAVA_TERNARY_EXPRESSION;

extern YAPP_RULE JAVA_CONDITIONAL_OR_EXPRESSION;

extern YAPP_RULE JAVA_OR_EXPRESSION;

extern YAPP_RULE JAVA_CONDITIONAL_AND_EXPRESSION;

extern YAPP_RULE JAVA_AND_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_BIT_OR_EXPRESSION;

extern YAPP_RULE JAVA_BIT_OR_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_BIT_XOR_EXPRESSION;

extern YAPP_RULE JAVA_BIT_XOR_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_BIT_AND_EXPRESSION;

extern YAPP_RULE JAVA_BIT_AND_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_RELATIONAL_EXPRESSION;

extern YAPP_RULE JAVA_RELATIONAL_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_INSTANCE_OF_EXPRESSION;

extern YAPP_RULE JAVA_INSTANCE_OF_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_ADDITIVE_EXPRESSION;

extern YAPP_RULE JAVA_REFERENCE_TYPE;

extern YAPP_RULE JAVA_ADDITIVE_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_MULTIPLICATIVE_EXPRESSION;

extern YAPP_RULE JAVA_MULTIPLICATIVE_EXPRESSION;

extern YAPP_RULE JAVA_OPTIONAL_SHIFT_EXPRESSION;

extern YAPP_RULE JAVA_SHIFT_EXPRESSION;

extern YAPP_RULE JAVA_UNARY_EXPRESSION;

extern YAPP_RULE JAVA_PREFIXED_EXPRESSION;

extern YAPP_RULE JAVA_CAST_EXPRESSION;

extern YAPP_RULE JAVA_POSTFIXED_EXPRESSION;

extern YAPP_RULE JAVA_PREFIX_OP;

extern YAPP_RULE JAVA_POST_FIX_OP;

extern YAPP_RULE JAVA_PRIMARY;

extern YAPP_RULE JAVA_QUALIFIED_EXPRESSION;

extern YAPP_RULE JAVA_ARRAY_ACCESS;

extern YAPP_RULE JAVA_ATOMIC;

extern YAPP_RULE JAVA_CLASS_TYPE_REFERENCE;

extern YAPP_RULE JAVA_LITERAL;

extern YAPP_RULE JAVA_BASIC_TYPE_CLASS_REFERENCE;

extern YAPP_RULE JAVA_VOID_CLASS_REFERENCE;

extern YAPP_RULE JAVA_THIS_METHOD_CALL;

extern YAPP_RULE JAVA_THIS;

extern YAPP_RULE JAVA_SUPER;

extern YAPP_RULE JAVA_SUPER_METHOD_CALL;

extern YAPP_RULE JAVA_SUPER_CONSTRUCTOR_CALL;

extern YAPP_RULE JAVA_SUPER_FIELD_ACCESS;

extern YAPP_RULE JAVA_NEW;

extern YAPP_RULE JAVA_CLASS_CREATOR;

extern YAPP_RULE JAVA_ARRAY_CREATOR;

extern YAPP_RULE JAVA_METHOD_CALL;

extern YAPP_RULE JAVA_ARRAY_INDEX;

extern YAPP_RULE JAVA_DIM_EXPR;

extern YAPP_RULE JAVA_BASIC_TYPE;

extern YAPP_RULE JAVA_NON_WILDCARD_TYPE_ARGUMENTS;

extern YAPP_RULE JAVA_CREATED_NAME;

extern YAPP_RULE JAVA_INITIALIZED_ARRAY_CREATOR;

extern YAPP_RULE JAVA_EMPTY_ARRAY_CREATOR;

extern YAPP_RULE JAVA_ARRAY_TYPE;

extern YAPP_RULE JAVA_DIM;

extern YAPP_RULE JAVA_ARRAY_INITIALIZER;

extern YAPP_RULE JAVA_TYPED_NAME;

extern YAPP_RULE JAVA_TYPE_NAME;

extern YAPP_RULE JAVA_ARRAY;

extern YAPP_RULE JAVA_BASIC_TYPE_ARRAY;

extern YAPP_RULE JAVA_QUALIFIED_CLASS_NAME_ARRAY;

extern YAPP_RULE JAVA_CLASS_NAME;

extern YAPP_RULE JAVA_TYPED_CLASS_NAME;

extern YAPP_RULE JAVA_TYPE_ARGUMENTS;

extern YAPP_RULE JAVA_TYPE_ARGUMENT;

extern YAPP_RULE JAVA_QUERY_TYPE;

extern YAPP_RULE JAVA_TYPE_PARAMETER;

extern YAPP_RULE JAVA_BOUND;

extern YAPP_RULE JAVA_ANNOTATION_TYPE_BODY;

extern YAPP_RULE JAVA_ANNOTATION_TYPE_ELEMENT_DECLARATION;

extern YAPP_RULE JAVA_ANNOTATION_METHOD;

extern YAPP_RULE JAVA_ANNOTATIONS_CONSTANTS;

extern YAPP_RULE JAVA_DEFAULT_VALUE;

extern YAPP_RULE JAVA_ELEMENT_VALUE;

extern YAPP_RULE JAVA_ANNOTATION_PARAMETERS;

extern YAPP_RULE JAVA_NORMAL_ANNOTATION_REST;

extern YAPP_RULE JAVA_SINGLE_ELEMENT_ANNOTATION_REST;

extern YAPP_RULE JAVA_ELEMENT_VALUE_PAIRS;

extern YAPP_RULE JAVA_ELEMENT_VALUE_PAIR;

extern YAPP_RULE JAVA_ELEMENT_VALUE_ARRAY_INITIALIZER;

extern YAPP_RULE JAVA_ELEMENT_VALUES;

extern YAPP_RULE JAVA_TEST_NO_ALPHA;

extern YAPP_RULE JAVA_SPACING;

extern YAPP_RULE JAVA_SPACES;

extern YAPP_RULE JAVA_BLOCK_COMMENT;

extern YAPP_RULE JAVA_NEW_LINE;

extern YAPP_RULE JAVA_LINE_COMMENT;

extern YAPP_RULE JAVA_FLOAT_LITERAL;

extern YAPP_RULE JAVA_LONG_LITERAL;

extern YAPP_RULE JAVA_INTEGER_LITERAL;

extern YAPP_RULE JAVA_CHAR_LITERAL;

extern YAPP_RULE JAVA_STRING_LITERAL;

extern YAPP_RULE JAVA_TRUE;

extern YAPP_RULE JAVA_FALSE;

extern YAPP_RULE JAVA_NULL;

extern YAPP_RULE JAVA_HEX_FLOAT;

extern YAPP_RULE JAVA_DECIMAL_FLOAT;

extern YAPP_RULE JAVA_SEMICOLON;

extern YAPP_NODE* javaParser_parse(JavaParser *parser);
extern JavaParser* javaParser_new(YAPP_BUFFER *inputBuffer);
extern JavaParser* javaParser_newManaged(YAPP_MEM_MANAGER *memoryManager, YAPP_BUFFER *inputBuffer);
extern void javaParser_free(JavaParser *parser);
extern void javaParser_setTraceParser(JavaParser *parser, YAPP_TRACE_PARSER *tracePath);
extern void javaParser_setTrace(JavaParser *parser, BOOL trace);
extern YAPP_PARSER_ERROR* javaParser_getMismatches(JavaParser *parser);
#endif
